name = "plinko-critique-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=plinko-critique.fr"
HMAC_KEY = "0808acb7b2e38fba082fc09ab8625a4525a29a22f15c0b4e06af4a6d00d137b7"
COOKIE_NAME = "347"
PLAY_PATH = "try"
BUTTON_ID = "p3ffee18d397cbbc9869b7af3a0fd8b9c"
GATE_SALT = "c4bef53eb0000586"
